# Numpy Assignment Questions

*Q1*. **What is a Python library? Why do we use Python libraries?**

**Answer**

A Python library is a collection of pre-written code and functionalities that can be reused by developers to perform common tasks. These libraries provide a set of modules, functions, and classes that can be imported into a Python script or program, saving developers time and effort by allowing them to leverage existing code rather than writing everything from scratch.

**Python libraries serve several purposes, including:**

Code Reusability: Libraries encapsulate code that performs specific functions or tasks. By using libraries, developers can avoid reinventing the wheel and leverage well-tested, optimized, and proven solutions.

Productivity: Libraries provide a way to quickly implement complex features without having to understand all the underlying details. This can significantly speed up the development process and reduce the amount of code a developer needs to write.

Community Contributions: The Python community actively develops and maintains a vast ecosystem of libraries. These libraries cover a wide range of domains, including web development, data science, machine learning, networking, and more. Developers can benefit from the collective knowledge and expertise of the community.

Standardization: Python libraries often follow standard conventions and best practices, promoting consistency and making it easier for developers to understand and work with code written by others

*Q2.* **What is the difference between Numpy array and List?**

**Answer**

NumPy arrays and Python lists are both used to store collections of data, but there are several key differences between them. Here are some of the main distinctions:

**1. Type of Elements:**
In a NumPy array, all elements must be of the same data type. This uniformity allows for more efficient storage and manipulation of data.
Python lists can contain elements of different data types in the same list.

**2. Memory Efficiency:**
NumPy arrays are more memory-efficient compared to Python lists. NumPy uses a contiguous block of memory to store data, while lists use pointers to objects in different locations.
NumPy arrays are more compact and allow for faster access to elements due to their fixed data type.

**3. Performance:** NumPy operations are implemented in C and are more efficient for numerical operations than the built-in Python list operations.
NumPy provides vectorized operations, which means that operations are performed on entire arrays, making them faster than equivalent operations on lists.

**4. Functionality:** NumPy arrays come with a variety of built-in functions and methods optimized for numerical operations, making it suitable for scientific computing and data manipulation.
Lists are more general-purpose and offer a wider range of functionalities but may not be as efficient for numerical computations.

**5. Syntax:** NumPy arrays provide a more concise and convenient syntax for mathematical and array operations.
Lists have a more flexible syntax but may require more explicit iterations for certain operations.

 *Q3.* **Find the shape, size and dimension of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np  #This line imports the "NumPy" library and assigns it the alias "np" for convenience

# Given array
myArray = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Shape of the array (number of rows and columns)
shape = myArray.shape

# Size of the array (total number of elements)
size = myArray.size

# Dimension of the array
dimension = myArray.ndim

# Print the results
print("Shape of the array:", shape)
print("Size of the array:", size)
print("Dimension of the array:", dimension)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


**Explaination:**

1. Import NumPy: first we import the NumPy library and assigns it the alias np.. NumPy is a powerful library for numerical computing in Python.

2. Define the Array: Here, we create a NumPy array using the np.array() function. The provided argument is a nested list representing a 2-dimensional array with 3 rows and 4 columns.

3. Retrieve Shape, Size, and Dimension:
                  shape = my_array.shape
                  size = my_array.size
                  dimension = my_array.ndim

shape: Returns a tuple representing the dimensions of the array. In this case, it's (3, 4), indicating 3 rows and 4 columns.
size: Returns the total number of elements in the array. For this array, it's 12.
dimension: Returns the number of dimensions of the array. This array is 2-dimensional.

4. Print the Results:  Finally, these print statements output the results to the console.


*Q4.* **Write python code to access the first row of the following array?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np  #This line imports the "NumPy library" and assigns it the alias "np" for convenience

# Given array
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Access the first row
first_row = my_array[0, :]

# Print the result
print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


**Explaination:**

1. Import NumPy: first we import the NumPy library and assigns it the alias np. NumPy is a powerful library for numerical computing in Python.

2. Define the Array: Here, we create a NumPy array using the np.array() function. The provided argument is a nested list representing a 2-dimensional array with 3 rows and 4 columns.

3. Access the First Row:
               first_row = my_array[0, :]

This line extracts the first row of the array using indexing. In NumPy, the syntax my_array[0, :] means to select all columns (:) in the first row (0).


4. Print the Result: This line prints the result to the console.

*Q5.* **How do you access the element at the third row and fourth column from the given numpy array?**

        [[1, 2, 3, 4]

        [5, 6, 7, 8],

        [9, 10, 11, 12]]

In [ ]:
import numpy as np  #This line imports the 'NumPy' library and assigns it the alias 'np'.

# Given array
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = my_array[2, 3]

# Print the result
print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


**Explaination:**

1. Import NumPy: first we import the NumPy library and assigns it the alias np. NumPy is a powerful library for numerical computing in Python.

2. Define the Array: Here, we create a NumPy array using the np.array() function. The provided argument is a nested list representing a 2-dimensional array with 3 rows and 4 columns.

3.Access the Element at the Third Row and Fourth Column: This line extracts the element at the third row (index 2) and fourth column (index 3) of the array.

4. Finally, these print statements output the results.

*Q6.* **Write code to extract all odd-indexed elements from the given numpy array?**

                    [[1, 2, 3, 4]
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]]

In [ ]:
import numpy as np

# Given array
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Initialize an empty list to store the results
result = []

# Iterate over rows and columns using nested loops
for row in my_array:
    for element in row:
        if element % 2 != 0 or element % 2 == 1:
            result.append(element)

# Convert the result to a NumPy array
result_array = np.array(result)

# Print the result
print("All odd and non-even elements:", result_array)


All odd and non-even elements: [ 1  3  5  7  9 11]


**Explaination:**

1. Import NumPy: first we import the NumPy library and assigns it the alias np. NumPy is a powerful library for numerical computing in Python.

2. Define the Array: Here, we create a NumPy array using the np.array() function. The provided argument is a nested list representing a 2-dimensional array with 3 rows and 4 columns.

3. Initialize an Empty List to Store Results:
       result = []

4. Iterate Over Rows and Columns using Nested Loops:
          for i in range(my_array.shape[0]):
             for j in range(my_array.shape[1]):
                element = my_array[i, j]
  Two nested loops are used to iterate over each element in the 2D array. The indices i and j represent the row and column indices, respectively.

5. Check if Element is Odd or Non-Even:
       if element % 2 != 0 or element % 2 == 1:
          result.append(element)

After the loops, the result list is converted to a NumPy array using np.array().

6. Finally, the result is printed.

*Q7.*  **How can you generate a ran^om 3x3 matrix with values between 0 and  1?**

In [ ]:
import numpy as np

# Create a 3x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Print the matrix
print(random_matrix)

[[0.76861278 0.78749727 0.77936734]
 [0.09015361 0.1544491  0.09792083]
 [0.59270651 0.80537295 0.44068275]]


**Explaination**

1. Import NumPy: first we import the NumPy library and assigns it the alias np. NumPy is a powerful library for numerical computing in Python.

2. Generate a Random 3x3 Matrix: The np.random.rand(3, 3) function generates a 3x3 matrix with random values from a uniform distribution between 0 (inclusive) and 1 (exclusive). Each element in the matrix is independently and uniformly sampled.

3. finally printing the result

*Q8.* **Describe the difference between np.random.rand and np.random.randn?**

The *np.random.rand* and *np.random.randn* functions in NumPy are both used for generating random numbers, but they differ in how they generate those numbers:

**np.random.rand:**

Generates random numbers from a uniform distribution over the half-open interval [0.0, 1.0).
Returns random samples that are uniformly distributed between 0 (inclusive) and 1 (exclusive).
All generated values have an equal probability of occurring.
Takes the shape of the output as separate argument (not as a tuple).

         np.random.rand(3, 4)  
         # Generates a 3x4 matrix of values between 0 and 1

      
**np.random.randn:**

Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
Returns random samples that follow a normal distribution with mean 0 and standard deviation 1.
Values are more likely to be close to 0 and decrease in probability as they move away from 0.
Takes the shape of the output as separate arguments (not as a tuple).

      np.random.randn(3, 4)
       # Generates a 3x4 matrix of values from a standard normal distribution



*Q9* **Write code to increase the dimension of the following array?**

              [[1, 2, 3, 4]
              [5, 6, 7, 8],
              [9, 10, 11, 12]]


In [ ]:
import numpy as np

# Given 2D array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase the dimension by adding a new axis
new_array = original_array[:, :, np.newaxis]

# Print the results
print("Original 2D array:")
print(original_array)
print("\nIncreased dimension array:")
print(new_array)


Original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Increased dimension array:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


**Explaination:**

1. Import NumPy: first we import the NumPy library and assigns it the alias np. NumPy is a powerful library for numerical computing in Python.

2. Define the Array: Here, we create a NumPy array using the np.array() function. The provided argument is a nested list representing a 2-dimensional array with 3 rows and 4 columns.

3. Creating new dimension: The np.newaxis is used to increase the dimension of the original_array by adding a new axis. In this case, [:, :, np.newaxis] adds a new axis along the third dimension (axis 2)

4. and finally printing the result.

*Q10* **How to transpose the following array in NumPy?**

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose using numpy.transpose
transposed_array1 = np.transpose(original_array)

# Transpose using .T attribute
transposed_array2 = original_array.T

# Print the results
print("Original array:")
print(original_array)
print("\nTransposed array (using numpy.transpose):")
print(transposed_array1)
print("\nTransposed array (using .T attribute):")
print(transposed_array2)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array (using numpy.transpose):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed array (using .T attribute):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Explaination:**

1. Import NumPy: first we import the NumPy library and assigns it the alias np. NumPy is a powerful library for numerical computing in Python.

2. Define the Array: Here, we create a NumPy array using the np.array() function. The provided argument is a nested list representing a 2-dimensional array with 3 rows and 4 columns.

3. Transposed_array1 = np.transpose(original_array) and transposed_array2 = original_array.T : This line uses the numpy.transpose function to transpose the original_array. The numpy.transpose function takes an array as input and returns the transposed array. In this case, it swaps the rows and columns of the original array. The .T attribute is a shorthand for transposing the array.

4. The code then prints the original array and the transposed arrays using both methods.

*Q11* **Consider the following matrix:**

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
  1. Index wise multiplication
  2. matrix multiplication
  3. Add both the matrix
  4. Substract matrix B from A
  5. Divide Matrix B by A

In [ ]:
import numpy as np

# Given matrices
matrix_A = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Index wise multiplication
index_wise_multiplication = matrix_A * matrix_B

# Matrix multiplication
matrix_multiplication = np.dot(matrix_A, matrix_B.T)

# Add both matrices
addition_result = matrix_A + matrix_B

# Subtraction of matrix B from A
subtraction_result = matrix_A - matrix_B

# Divide matrix B by A
division_result = matrix_B / matrix_A

# Print the results
print("Index wise multiplication:")
print(index_wise_multiplication)

print("\nMatrix multiplication:")
print(matrix_multiplication)

print("\nAddition of both matrices:")
print(addition_result)

print("\nSubtraction of matrix B from A:")
print(subtraction_result)

print("\nDivision of matrix B by A:")
print(division_result)


Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition of both matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of matrix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division of matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


*Q12* **Which function in Numpy can be used to swap the byte order of an array?**

**Answer**

In NumPy, we can use the np.byteswap function to swap the byte order of an array. This function is particularly useful for dealing with binary data where the endianness (byte order) of the data needs to be adjusted.

In [ ]:
# Example
import numpy as np

# Create a NumPy array with integer values
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Print the results
print("Original array:", original_array)
print("Swapped byte order array:", original_array.byteswap(True))

Original array: [1 2 3 4]
Swapped byte order array: [16777216 33554432 50331648 67108864]


**Expaination:**

Here, the *byteswap* method is applied to the original_array. The True argument indicates that the byte order should be swapped. The byteswap method is used to change the byte order of the elements in the array.

 the *byteswap* method modifies the array in place and returns a reference to the modified array. If you want to preserve the original array, you might want to create a copy before applying the byteswap operation.

*Q13*. **What is the significance of the np.linalg.inv function?**

**Answer**

The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. In linear algebra, the inverse of a matrix A, denoted as A^(-1), is a matrix such that when it is multiplied by the original matrix A, the result is the identity matrix.

Mathematically, if A is a square matrix and A^(-1) is its inverse, then:

A⋅A
(
 −1)=A
(
 −1)⋅A=I

In [1]:
import numpy as np

# Create a square matrix
A = np.array([[2, 1],
              [7, 4]])

# Calculate the inverse
A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)


Original Matrix:
[[2 1]
 [7 4]]

Inverse Matrix:
[[ 4. -1.]
 [-7.  2.]]


*Q14.* **What does the np.reshape function do, and how is it used?**

**Answer**

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array to a new shape, provided that the total number of elements remains the same. Reshaping is a useful operation when you want to change the dimensions of an array,

              numpy.reshape(a, newshape, order='C')  #The basic syntax of np.reshape is as follows:


In [ ]:
import numpy as np

# Create a one-dimensional array with 12 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the array to a 3x4 matrix
reshaped_arr = np.reshape(arr, (3, 4))

print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(reshaped_arr)


*Q15*. What is broadcasting in Numpy?

**Answer**

Broadcasting in NumPy is a powerful feature that allows for performing operations on arrays of different shapes and sizes, without explicitly creating copies or reshaping the arrays. This capability enables you to write more concise and readable code when working with arrays.

*The broadcasting rule in NumPy follows these steps when performing element-wise operations on arrays with different shapes:*
 1. If the arrays have a different number of dimensions, pad the smaller-dimensional array's shape with ones on its left side until both shapes have the same length.

 2. Compare the sizes of the corresponding dimensions. Two dimensions are compatible for broadcasting when:
      They are equal, or
      One of them is 1.
 3. If the sizes in a dimension are not compatible and none of them is 1, a ValueError will be raised, indicating that the operation is not possible.

 4. After broadcasting, perform the element-wise operation.

In [2]:
# Here is a simple example.

import numpy as np

# Example 1:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

result = a * b  # Broadcasting happens here

print(result)
# Output: [2. 4. 6.]


[2. 4. 6.]
